In [4]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn import linear_model

In [16]:
df = pd.read_csv('home_price_multi.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [17]:
import math
median_bd = math.floor(df.bedrooms.median())
df.bedrooms = df.bedrooms.fillna(median_bd)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [20]:
reg.intercept_

383724.99999999983

In [21]:
reg.predict([[3000,3,40]])

array([ 444400.])

In [27]:
d = pd.read_csv('home_price_multi_test.csv')
d

area  bedrooms  age
0  2600         3   15
1  3000         4   10
2  3400         5   20
3  3600         4   25
4  4000         5    6

In [29]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [30]:
reg.predict(d)

array([ 560125.,  623125.,  583750.,  603100.,  761650.])